### ISSUE TITLE
Paginator背景图

### ISSUE THREAD

**Issue by uicestone** [uicestone/TNF#2]
@Natt7 images/ 下有normal.png, over.png和selected.png三张图，根据我们的尺寸调整一下。

**Comment by Natt7** [comment]
![select](https://cloud.githubusercontent.com/assets/5966927/6769872/58a7fe58-d0e7-11e4-99d6-6fa5c1746bc2.png)
![nomal](https://cloud.githubusercontent.com/assets/5966927/6769873/58abbc64-d0e7-11e4-91cc-058631873093.png)
![over](https://cloud.githubusercontent.com/assets/5966927/6769874/58bd6aa4-d0e7-11e4-9a35-73846264e89f.png)

**Comment by uicestone** [comment]
邮件我吧，图下了名字看不见。为啥有两张是71px？没搞错？ @Natt7
